<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Harmon Bhasin">
<meta name="author" content="Michael McLaren">
<meta name="author" content="Lennart Justen">
<meta name="dcterms.date" content="2025-02-03">

<title>Exploring Blood-Based Biosurveillance, Part 3: The Blood Virome</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-79108a0fc1995748cbd19a5b0e3e3e7c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: black;
      }
</style>


</head>

<body>

<div id="quarto-search-results"></div>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <div class="quarto-title-block"><div><h1 class="title">Exploring Blood-Based Biosurveillance, Part 3: The Blood Virome</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Authors</div>
      <div class="quarto-title-meta-contents">
               <p>Harmon Bhasin </p>
               <p>Michael McLaren </p>
               <p>Lennart Justen </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 3, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#the-mgs-datasets" id="toc-the-mgs-datasets" class="nav-link" data-scroll-target="#the-mgs-datasets">The MGS datasets</a></li>
  <li><a href="#computational-methods" id="toc-computational-methods" class="nav-link" data-scroll-target="#computational-methods">Computational methods</a></li>
  <li><a href="#kingdom-level-composition" id="toc-kingdom-level-composition" class="nav-link" data-scroll-target="#kingdom-level-composition">Kingdom-level composition</a></li>
  <li><a href="#human-infecting-viruses" id="toc-human-infecting-viruses" class="nav-link" data-scroll-target="#human-infecting-viruses">Human-infecting viruses</a></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#appendix-1:-dataset-descriptions" id="toc-appendix-1:-dataset-descriptions" class="nav-link" data-scroll-target="#appendix-1\:-dataset-descriptions">Appendix 1: Dataset descriptions</a></li>
  <li><a href="#appendix-2:-human-infecting-virus-genera" id="toc-appendix-2:-human-infecting-virus-genera" class="nav-link" data-scroll-target="#appendix-2\:-human-infecting-virus-genera">Appendix 2: Human-infecting virus genera</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><em>This is the third post in a series of blogs exploring blood-based biosurveillance for novel pathogen detection as part of the NAO’s effort to <a href="https://naobservatory.org/evaluating-biosurveillance-approaches">evaluate different biosurveillance</a> approaches. We once again thank our colleagues at the NAO, particularly Jeff Kaufman and Will Bradshaw, for their valuable feedback.</em></p>
<section id="summary" class="level1">
<h1>Summary</h1>
<p>To help assess the effectiveness of blood-based biosurveillance, we reanalyzed six publicly available whole blood and plasma metagenomic sequencing datasets, examining both kingdom-level composition and the prevalence and relative abundance of human-infecting viruses (HVs). These studies represent diverse sample processing methods, donor populations, and sequencing approaches. Our analysis revealed that sample type and processing methods can strongly influence viral detection. Plasma samples consistently showed higher total HV relative abundance than whole blood, particularly when employing additional filtration to remove human nucleic acid, though this step may reduce detection of primarily intracellular viruses.</p>
<p><em>Anelloviridae</em> was the most consistently detected viral family, appearing in most datasets with particularly high prevalence in plasma samples. We also detected viral families associated with intracellular latent infections, including <em>Orthoherpesviridae</em> and <em>Retroviridae</em>. These findings align well with known epidemiology of blood-borne and latent viral infections. Common respiratory viruses were largely absent, suggesting that a biosurveillance system aiming for coverage of the full range of human viruses will need to combine multiple sample types.</p>
</section>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Untargeted metagenomic sequencing (MGS) of blood-derived samples could enable greatly improved early detection of novel viral threats. In our previous posts, we examined the <a href="https://naobservatory.org/blog/exploring-blood-biosurveillance-part1">biological characteristics</a> of blood and identified <a href="https://naobservatory.org/blog/exploring-blood-biosurveillance-part2">promising strategies</a> for accessing samples in high-throughput from the U.S. blood supply system. In this post we investigate the human blood virome by reanalyzing a diverse set of MGS datasets to better understand pathogen presence and relative abundance (RA) – key metrics for determining the sensitivity, cost, and robustness of any future blood-based biosurveillance system.</p>
<p>We reanalyze six publicly available MGS datasets, drawn from both whole blood and plasma. We apply a consistent computational pipeline to characterize the blood virome, examining the RA and prevalence of human-infecting viruses (HV) across studies with distinct sample types, sample processing methods, and donor populations. Our findings help quantify the potential role of blood-based surveillance within a broader system for detecting emerging pathogens, complementing existing approaches like wastewater and respiratory swab sampling.</p>
</section>
<section id="the-mgs-datasets" class="level1">
<h1>The MGS datasets</h1>
<p>We sought MGS data to characterize the blood virome of healthy donor populations<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> that could represent eligible blood and plasma donors, looking for three datasets for each sample type (whole blood and plasma). After an initial literature review, we excluded a number of suitable studies due to the lack of publicly available data (1) or the requirement of onboarding procedures to access the data (2). We ultimately relaxed the requirement for data strictly from healthy donors and selected six publicly accessible, short read Illumina MGS datasets to re-analyze (Table 1).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: left;">Sample type</th>
<th style="text-align: left;">Country†</th>
<th style="text-align: left;">Donor description</th>
<th style="text-align: left;">Samples (Contributing individuals)</th>
<th style="text-align: left;">Total read pairs (Avg. per sample)</th>
<th style="text-align: left;">Sample prep optimization for viruses?</th>
<th style="text-align: left;">Nucleic acid sequenced</th>
<th style="text-align: left;">Read type</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cebriá-Mendoza et al.&nbsp;(3)</td>
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Spain</td>
<td style="text-align: left;">Healthy</td>
<td style="text-align: left;">60 (587)</td>
<td style="text-align: left;">230M (3.8M)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">DNA+RNA</td>
<td style="text-align: left;">2x150 bp</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thijssen et al.&nbsp;(4)</td>
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Iran</td>
<td style="text-align: left;">Healthy</td>
<td style="text-align: left;">21 (100)</td>
<td style="text-align: left;">116M(5.6M)</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">DNA+RNA</td>
<td style="text-align: left;">2x150 bp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mengyi et al.&nbsp;(5)</td>
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">China</td>
<td style="text-align: left;">Healthy</td>
<td style="text-align: left;">201 (≤10,720††)</td>
<td style="text-align: left;">3.4B(17.1M)</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">DNA</td>
<td style="text-align: left;">2x150 bp</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aydillo et al.&nbsp;(6)</td>
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Healthy</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">1.7B (32.8M)</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">RNA</td>
<td style="text-align: left;">2x100 bp</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O’Connell (7)</td>
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Emergency room patients with chronic health condition</td>
<td style="text-align: left;">138</td>
<td style="text-align: left;">3.1B (22.5M)</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">RNA</td>
<td style="text-align: left;">2x150 bp</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thompson et al.&nbsp;(8)</td>
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Hospitalized COVID-19 patients and healthy controls<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></td>
<td style="text-align: left;">417</td>
<td style="text-align: left;">27.7B (66.4M)</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">RNA</td>
<td style="text-align: left;">2x100 bp</td>
</tr>
</tbody>
</table>
<p><strong>Table 1</strong>: Key characteristics of the six metagenomic sequencing datasets analyzed in this study. Numbers in parentheses indicate total donors contributing to pooled samples. Datasets are ordered by increasing percentage of human reads (see Table 2). Detailed descriptions of each study available in <a href="#appendix-1:-dataset-descriptions">Appendix 1</a>. †: Country denotes countries where the donations occurred. ††: The total number of donations that contributed to all samples is 10,720; the authors do not state whether some individuals contributed multiple donations.</p>
<p>The datasets included were originally generated for a variety of purposes, ranging from characterizing the healthy human blood virome (3–5) to studying host responses during vaccination (6), evaluating biomarkers for chronic conditions (7), and investigating molecular signatures of long COVID (8). As a result, these studies exhibit substantial methodological differences that complicate direct comparisons between plasma and whole blood as sample types.</p>
<ul>
<li><p><strong>Donor population:</strong> The plasma studies analyzed samples from healthy donors across different countries, with all studies using pooled samples from multiple donors within the same region. In contrast, the whole blood studies analyzed individual (unpooled) samples from both healthy and ill participants exclusively within the U.S.</p></li>
<li><p><strong>Sample processing:</strong> The plasma studies had varying levels of sample processing to remove human cellular material. While the methods used to separate plasma from whole blood in Cebrià-Mendozá et al.&nbsp;(3) and Thijssen et al.&nbsp;(4) were not specified, both studies employed additional viral enrichment protocols on their plasma samples, including filtration of remaining host cells (1.0 μm and 0.8 μm respectively) and nuclease treatment of unprotected nucleic acids. In contrast, Mengyi et al.&nbsp;(5) separated plasma from whole blood using centrifugation and employed an additional ultracentrifugation step to concentrate viruses and other material into a pellet, without filtration or nuclease treatment steps. The whole blood studies used standard RNA sequencing protocols focused on host transcriptomics, with cell lysis, RNA extraction, and depletion of ribosomal and <a href="https://en.wikipedia.org/wiki/Globin">globin</a> RNA.</p></li>
<li><p><strong>Sequencing approach:</strong> Whole blood studies using RNA sequencing exclusively at higher depth (average reads/sample ranging from 22-66M), while plasma studies used either DNA sequencing alone or combined DNA/RNA approaches at lower depth (average reads/sample ranging from 3-17M). While RNA-only studies can still detect DNA viruses through their transcripts, and DNA studies can capture some RNA viruses through reverse-transcribed DNA intermediates, the nucleic acid type sequenced is certain to impact detection sensitivity of different viral families.</p></li>
</ul>
<p>These differences in sample preparation, donor population, and sequencing approach make it challenging to isolate the effects of sample type on taxonomic composition. Some studies have more successfully controlled for these variables in direct comparisons of whole blood and plasma (9–12), though their underlying data is often restricted. Nevertheless, analyzing these diverse datasets through a single computational pipeline allows us to observe consistent trends and assess variation across methodologies. Further relevant details on the studies are described in <a href="#appendix-1:-dataset-descriptions">Appendix 1</a>.</p>
</section>
<section id="computational-methods" class="level1">
<h1>Computational methods</h1>
<p>We processed all datasets through a modified version of the viral metagenomic sequencing pipeline (<a href="https://github.com/harmonbhasin/mgs-workflow">v2.2.1</a>) described in Grimm et al.&nbsp;(13). To reduce computational requirements, we simplified the adapter trimming steps by using only FASTP rather than the original combination of FASTP, Cutadapt, and Trimmomatic.</p>
<p>The pipeline consists of two workflows: the taxonomic profiling workflow and the viral identification workflow. The taxonomic profiling workflow uses Kraken2 to assign reads to the least common ancestor (based on NCBI taxonomy) of matched genomes in the Kraken2 Standard database, which includes RefSeq prokaryotic, viral, and vector genomes along with the human genome. Results from this workflow determine the kingdom-level composition shown in Table 1. Since the database lacks non-human eukaryotic reference genomes, reads from such organisms are expected to remain unassigned.</p>
<p>The viral-identification workflow maps reads with Kraken2 (also with the Standard database) and aligns reads using Bowtie2 to an expanded database of human-infecting virus genomes from GenBank, reporting putative human-infecting virus reads based on the condition that the read aligns by Bowtie2 to a human virus and is not mapped by Kraken2 to a taxon that is not a human virus. We use the Bowtie2 assignment as the taxonomic assignment of a read.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>We applied additional filtering to taxonomic assignments in our downstream analysis. First, we removed reads from the Cebrià-Mendoza et al.&nbsp;(3) dataset that Kraken2 assigned to <em>Microviridae</em> or <em>Rhabdoviridae</em> families, which originated from Phi-X and Vesicular Stomatitis Virus spike-in controls. Second, we removed SARS-CoV-2 reads from the Thijssen et al.&nbsp;(4) and Mengyi et al.&nbsp;(5), as these were likely laboratory contaminants given that samples were collected before the COVID-19 pandemic (2012-2018).</p>
<p>Complete analysis code and documentation are available in our public GitHub <a href="https://github.com/naobservatory/blood-blog-post-3">repository</a>.</p>
</section>
<section id="kingdom-level-composition" class="level1">
<h1>Kingdom-level composition</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sample type</th>
<th style="text-align: left;">Dataset</th>
<th style="text-align: left;">Unassigned</th>
<th style="text-align: left;">Human</th>
<th style="text-align: left;">Bacterial</th>
<th style="text-align: left;">Archaeal†</th>
<th style="text-align: left;">Viral</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Cebrià-Mendoza et al.&nbsp;(3)</td>
<td style="text-align: left;">43%</td>
<td style="text-align: left;">2.0%</td>
<td style="text-align: left;">51%</td>
<td style="text-align: left;">0.034%</td>
<td style="text-align: left;">4.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Thijssen et al.&nbsp;(4)</td>
<td style="text-align: left;">73%</td>
<td style="text-align: left;">22%</td>
<td style="text-align: left;">4.5%</td>
<td style="text-align: left;">0.013%</td>
<td style="text-align: left;">0.034%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Mengyi et al.&nbsp;(5)</td>
<td style="text-align: left;">1.3%</td>
<td style="text-align: left;">98.4%</td>
<td style="text-align: left;">0.27%</td>
<td style="text-align: left;">0.00096%</td>
<td style="text-align: left;">0.013%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">Aydillo et al.&nbsp;(6)</td>
<td style="text-align: left;">0.35%</td>
<td style="text-align: left;">99.54%</td>
<td style="text-align: left;">0.11%</td>
<td style="text-align: left;">0.00061%</td>
<td style="text-align: left;">0.00028%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">O’Connell (7)</td>
<td style="text-align: left;">0.087%</td>
<td style="text-align: left;">99.86%</td>
<td style="text-align: left;">0.050%</td>
<td style="text-align: left;">0.000038%</td>
<td style="text-align: left;">0.00011%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">Thompson et al.&nbsp;(8)</td>
<td style="text-align: left;">0.11%</td>
<td style="text-align: left;">99.87%</td>
<td style="text-align: left;">0.013%</td>
<td style="text-align: left;">0.000074%</td>
<td style="text-align: left;">0.00027%</td>
</tr>
</tbody>
</table>
<p><strong>Table 2</strong>: Kingdom-level taxonomic composition showing percentage of reads assigned to each kingdom after random subsampling to 1 million read pairs per sample. †: Archaea are generally not expected in human blood (14); these reads may represent laboratory contamination or misassignment during taxonomic classification.</p>
<p>Datasets varied substantially in kingdom composition (Table 2). Whole blood datasets showed remarkable consistency, with human reads exceeding 99.5% of sequences and minimal variation in non-eukaryotic kingdoms. In contrast, plasma datasets exhibited greater heterogeneity. Two plasma studies (3,4) that enriched for viruses by filtering out eukaryotic cells showed lower human relative abundance (RA) and higher non-eukaryotic kingdom RA. The third plasma study (5), which only concentrated samples via ultracentrifugation without filtration, showed intermediate values. Even without enrichment, plasma datasets consistently contained a greater fraction of non-human sequences than whole blood, with the viral fraction in Mengyi et al.&nbsp;(5) exceeding whole blood datasets by two orders of magnitude.</p>
<p>The kingdom-level composition indicates that both sample type and sample processing methods have a substantial effect on human RA, with lower human RA corresponding to significantly higher viral RA. Plasma should inherently contain less human nucleic acid than whole blood due to its cell-free nature, though depending on the initial state of the plasma it seems this advantage can be further enhanced through a filtration step.</p>
</section>
<section id="human-infecting-viruses" class="level1">
<h1>Human-infecting viruses</h1>
<p><img src="../img/2025-01-31_figure1.png" class="img-fluid" alt="hv-dataset"> <strong>Figure 1</strong>: Distribution of human-infecting virus relative abundance across all samples in six studies. Each point represents a single sample. Boxplots show the distribution including samples with zero HV reads (box: 25th-75th percentiles, line: median, whiskers: extend to 1.5× interquartile range). For studies with many zeros, the median and potentially the entire boxplot may collapse to zero. Numbers underneath the study names denote the percentage of samples with at least one HV read.</p>
<p>Total human-infecting virus (HV) RA differed markedly between studies (Figure 1) in a manner consistent with the kingdom-level composition. Datasets that had lower human RA tended to have more samples with HV reads and higher total-HV RA in those samples. Whole blood samples generally showed low HV RA, with a maximum of 1.35×10^(-4) across all samples and with the majority of samples in each dataset containing no HV reads. Plasma samples showed higher RA, with median values ranging from 10^(-6) to 10^(-2) across studies and only a small fraction of samples containing no HV reads. Cebriá-Mendoza et al.&nbsp;(3) had the highest median RA of 6.06×10^(-3) consistent with their success in removing human nucleic acids during sample processing.</p>
<p>Across datasets, the presence and RA of total HVs increased inversely to the fraction of human reads in the dataset, suggesting that presence and RA of HVs is driven by the ability for a given sample type and processing protocol to yield non-human reads. The higher proportion of samples with HV reads in plasma datasets also likely reflects the use of pooled samples, which increases the chance that an HV will be present in the sample.</p>
<p><img src="../img/2025-01-31_figure2.png" class="img-fluid" alt="hv-composition"> <strong>Figure 2</strong>: Distribution of human-infecting virus families across datasets, showing the average relative abundance of each viral family per dataset. Families contributing less than 5% to any single dataset are grouped into the “Other” category.</p>
<p>To understand the viral composition across datasets, we analyzed which virus families contributed to the human-infecting virus (HV) reads (Figure 2). We found substantial variation in the dominant viral families, both between and within sample types. In the two plasma studies that used filtration to enrich for viral nucleic acids (3,4), <a href="https://en.wikipedia.org/wiki/Anelloviridae"><em>Anelloviridae</em></a> was the most prevalent family. In the third plasma study (5)<em>, Parvoviridae</em> was the most abundant. Among whole blood studies, <a href="https://en.wikipedia.org/wiki/Flaviviridae"><em>Flaviviridae</em></a> dominated in two datasets (6,8) but was notably absent in the third (7). The substantial heterogeneity in the taxonomic composition of HV reads appears to only be partly explained by sample type, with other factors such as sample preparation, sequencing depth, and donor population profile likely accounting for further differences.</p>
<p><img src="../img/2025-01-31_figure3.png" class="img-fluid" alt="hv-ra-prev"> <strong>Figure 3</strong>: Detection of human-infecting virus (HV) families across whole blood and plasma datasets, including only families found in at least five samples. Left panel: Prevalence of each viral family, shown as the percentage of samples containing at least one viral read. Right panel: Relative abundance of viral families in positive samples.</p>
<p>Our analysis identified 16 human virus (HV) families across all datasets, with 10 families detected in at least five samples (Figure 3). The relative abundance (RA) of detected viruses varied widely, ranging from 10^(-8) to 10^(-1). Whole blood samples generally showed lower non-zero RA values, partly due to their greater sequencing depth (Table 1) which enables detection of rarer sequences.</p>
<p><em>​​Anelloviridae</em> emerged as the most consistently detected family, appearing in five of six datasets with particularly high prevalence (&gt;75%) in plasma samples. Their relative abundance showed substantial variation, spanning up to three orders of magnitude within individual datasets. This high prevalence aligns with current understanding—Anelloviruses are nearly ubiquitous in humans, maintain persistent replication in T lymphocytes, and produce an estimated 10^(10) virions daily (15–17).</p>
<p>We detected several viral families known to establish persistent infections in humans. <a href="https://en.wikipedia.org/wiki/Retrovirus"><em>Retroviridae</em></a> and <a href="https://en.wikipedia.org/wiki/Herpesviridae"><em>Orthoherpesviridae</em></a> were found across multiple datasets, consistent with their high prevalence in human populations. The detected <em>Orthoherpesviridae</em> genera (<a href="#appendix-2:-human-infecting-virus-genera">Appendix 2</a>) correspond to common herpesviruses such as HSV-1/2, Epstein-Barr virus (EBV; infecting ~90% of adults worldwide), and human cytomegalovirus (HCMV; ~80% prevalence) (18,19). Within <em>Retroviridae</em>, we identified sequences from the <em>Lentivirus</em> genus, which includes HIV.</p>
<p>Other persistent viral families detected include <a href="https://en.wikipedia.org/wiki/Papillomaviridae"><em>Papillomaviridae</em></a>, <a href="https://en.wikipedia.org/wiki/Polyomaviridae"><em>Polyomaviridae</em></a>, and <a href="https://en.wikipedia.org/wiki/Flaviviridae"><em>Flaviviridae</em></a>. <em>Papillomaviridae</em> sequences appeared at low prevalence (&lt;10%) in both sample types, likely reflecting either human papillomavirus (HPV) persistence in blood cells or shedding from infected tissues (20,21). The <em>Polyomaviridae</em> family, containing human polyomaviruses which are widespread (~80% prevalence among adults; (22)) and primarily asymptomatic, was also detected in both blood and plasma. Polyomaviruses can replicate at low levels within lymphocytes and persist in bone marrow or kidneys (23). <em>Flaviviridae</em>, represented primarily by human pegivirus (<a href="#appendix-2:-human-infecting-virus-genera">Appendix 2</a>), appeared in more than 25% of samples in Cebriá-Mendoza et al.&nbsp;(3). This lymphocyte-infecting virus is non-pathogenic, with prevalence estimates ranging from 1.7% in North America to 9.1% in South America (24).</p>
<p>Absent from both whole blood and plasma samples were viral families like <em>Picornaviridae</em> (including rhinoviruses) and <em>Orthomyxoviridae</em> (including influenza viruses) responsible for common respiratory infections. This is consistent with our <a href="https://naobservatory.org/blog/exploring-blood-biosurveillance-part1">previous investigation</a> which found that these viruses typically appear in blood only during severe infections. The sole exception was <a href="https://en.wikipedia.org/wiki/Coronaviridae"><em>Coronaviridae</em></a> (including coronaviruses) in the Thompson et al.&nbsp;(8) dataset, which specifically included hospitalized COVID-19 patients. While we detected <a href="https://en.wikipedia.org/wiki/Adenoviridae"><em>Adenoviridae</em></a>, a family of viruses that can cause respiratory illness, these viruses have broader tissue tropism and can establish lymphocyte latency (25), distinguishing them from typical respiratory pathogens.</p>
<p>Sample processing methods appear to have significantly influenced viral detection patterns. Plasma studies using filtration to remove eukaryotic cells (3,4) achieved the highest relative abundances for HV reads (Figure 1), particularly <em>Anelloviridae</em>. However, these filtered plasma studies missed virus families like <em>Retroviridae</em> and <em>Orthoherpesviridae</em> that were detected in studies retaining more human nucleic acid content<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> – namely the whole blood studies and Mengyi et al.&nbsp;(5), a plasma study which did not employ filtering of eukaryotic cells. Mengyi et al.&nbsp;(5) showed an intermediate pattern overall, with lower <em>Anelloviridae</em> abundance than filtered plasma studies but higher than whole blood studies, while still detecting <em>Orthoherpesviridae</em> and <em>Retroviridae</em>.</p>
<p>The varying detection patterns observed for the <em>Retroviridae</em> and <em>Orthoherpesviridae</em> families align with their biological characteristics, with possible implications for blood-based biosurveillance. These viral families establish long-term intracellular latent infections through distinct mechanisms – retroviruses integrate into the host genome as <a href="https://en.wikipedia.org/wiki/Provirus">proviral</a> DNA, while herpesviruses persist as nuclear <a href="https://en.wikipedia.org/wiki/Episome">episomes</a> (viral plasmids in the nucleus). Their detection in both whole blood and unfiltered plasma samples indicates that preserving material from within human cells is critical for detecting viruses in predominantly intracellular states. Whole blood samples provide the most reliable source of intracellular content, as plasma samples may vary substantially in their cellular content depending on collection methods and pre-processing done before samples are received.</p>
<p>However, detecting viruses in intracellular states may be less critical for early warning of novel emerging pathogens. During initial infection and active spread, blood-borne pathogens would likely be present in plasma regardless of their ultimate cellular tropism, as viruses must pass through the extracellular space to establish and spread their infection. Even latent viruses periodically reactivate with associated viral shedding into plasma (26,27). These biological patterns suggest that filtered plasma samples could effectively capture novel blood-borne pathogens while benefiting from the greater viral sensitivity associated with removing human nucleic acid content.</p>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>Our reanalysis of six publicly available MGS datasets provides new insights into the potential utility of blood-based biosurveillance. Sample type and processing methods strongly influence viral detection—plasma samples consistently showed higher viral relative abundance than whole blood, and viral enrichment through filtration further improved detection of some viral families. However, this enhanced sensitivity through filtration appears to come with tradeoffs, potentially reducing detection of primarily intracellular viruses like <em>Orthoherpesviridae</em> and <em>Retroviridae</em>.</p>
<p>The detected viruses align well with known epidemiology of blood-borne and latent viral infections, suggesting MGS of blood and plasma can reliably detect an important subset of human-infecting viruses. However, common respiratory and gastrointestinal viruses were notably absent from samples from healthy donors, indicating that blood-based surveillance may be most effective as part of a complementary system incorporating other sample types like respiratory swabs and wastewater.</p>
<p>Several limitations of our analysis suggest directions for future work. Contamination is a significant concern in metagenomic sequencing studies, as outside nucleic acid can be introduced during sample collection, processing, and library preparation, altering the taxonomic profile and potentially leading to false positive detections. A more rigorous analysis of potential contamination, including examining control samples and systematic removal of laboratory contaminants, would strengthen confidence in our viral detections. Additionally, our ability to causally assign the differences in viral presence and abundance to sample type and viral enrichment is limited by the differences among studies in donor population and other differences in sample processing and sequencing methods. Statistical modeling that accounts for both sequencing depth and expected viral prevalence in donor populations could provide estimates of detection sensitivity for a given cost or amount of sequencing (13). However, obtaining accurate estimates of viral prevalence is challenging. Studies directly comparing whole blood and plasma fractions from the same individuals using the same sequencing method would enable more definitive conclusions about sample type differences, as they would allow us to eliminate variation in viral prevalence and sequencing protocol.</p>
<p>Our work has shown that blood captures a considerable diversity of human-infecting viruses and that sample type and processing methods greatly impact viral relative abundance. The results suggest that if the sample collection and processing was optimized, blood could provide sensitive detection of pathogens not readily detectable in wastewater or nasal swabs. Overall, we’re excited about the role that blood-based biosurveillance could play in our broader early detection network and are interested in hearing about potential partners in this space.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>1. Moustafa A, Xie C, Kirkness E, Biggs W, Wong E, Turpaz Y, et al.&nbsp;The blood DNA virome in 8,000 humans. PLoS Pathog [Internet]. 2017 Mar 22;13(3):e1006292. https://doi.org/10.1371/journal.ppat.1006292</p>
<p>2. Tan CCS, Ko KKK, Chen H, Liu J, Loh M, Chia M, et al.&nbsp;No evidence for a common blood microbiome based on a population study of 9,770 healthy humans. Nature Microbiology [Internet]. 2023 May;8(5):973–85. https://doi.org/10.1038/s41564-023-01350-w</p>
<p>3. Cebriá-Mendoza M, Bracho MA, Arbona C, Larrea L, Díaz W, Sanjuán R, et al.&nbsp;Exploring the Diversity of the Human Blood Virome. Viruses [Internet]. 2021 Nov 21;13(11). https://doi.org/10.3390/v13112322</p>
<p>4. Thijssen M, Khamisipour G, Maleki M, Devos T, Li G, Van Ranst M, et al.&nbsp;Characterization of the Human Blood Virome in Iranian Multiple Transfused Patients. Viruses [Internet]. 2023 Jun 23;15(7). https://doi.org/10.3390/v15071425</p>
<p>5. Mengyi Z, Yuhui L, Zhan G, Anqing L, Yujia L, Shilin L, et al.&nbsp;Plasma metagenomics reveals regional variations of emerging and re-emerging pathogens in Chinese blood donors with an emphasis on human parvovirus B19. One Health [Internet]. 2023 Dec;17:100602. https://doi.org/10.1016/j.onehlt.2023.100602</p>
<p>6. Aydillo T, Gonzalez-Reiche AS, Stadlbauer D, Amper MA, Nair VD, Mariottini C, et al.&nbsp;Transcriptome signatures preceding the induction of anti-stalk antibodies elicited after universal influenza vaccination. NPJ Vaccines [Internet]. 2022 Dec 10 [cited 2024 Oct 9];7(1):160. https://doi.org/10.1038/s41541-022-00583-w</p>
<p>7. O’Connell GC. Dataset including whole blood gene expression profiles and matched leukocyte counts with utility for benchmarking cellular deconvolution pipelines. BMC Genom Data [Internet]. 2024 May 7 [cited 2024 Oct 9];25(1):45. https://doi.org/10.1186/s12863-024-01223-z</p>
<p>8. Thompson RC, Simons NW, Wilkins L, Cheng E, Del Valle DM, Hoffman GE, et al.&nbsp;Molecular states during acute COVID-19 reveal distinct etiologies of long-term sequelae. Nat Med [Internet]. 2023 Jan [cited 2024 Oct 9];29(1):236–46. https://doi.org/10.1038/s41591-022-02107-4</p>
<p>9. Flurin L, Wolf MJ, Fisher CR, Cano Cevallos EJ, Vaillant JJ, Pritt BS, et al.&nbsp;Pathogen Detection in Infective Endocarditis Using Targeted Metagenomics on Whole Blood and Plasma: a Prospective Pilot Study. Simner PJ, editor. J Clin Microbiol [Internet]. 2022 Sep 21;60(9). https://doi.org/10.1128/jcm.00621-22</p>
<p>10. Lau P, Cordey S, Brito F, Tirefort D, Petty TJ, Turin L, et al.&nbsp;Metagenomics analysis of red blood cell and fresh-frozen plasma units. Transfusion [Internet]. 2017 Jul;57(7):1787–800. https://doi.org/10.1111/trf.14148</p>
<p>11. Wang D, Zhang Z, Shen H, Jin F, Liang J, Shen D, et al.&nbsp;Comparison of plasma and blood cell samples in metagenomic next-generation sequencing for identification of the causative pathogens of fever. Heliyon [Internet]. 2024 Jun;10(11):e31677. https://doi.org/10.1016/j.heliyon.2024.e31677</p>
<p>12. Wu C, Yu X, Gai W, Liu Y, Qi Y, Zheng Y, et al.&nbsp;Diagnostic value of plasma and blood cells metagenomic next-generation sequencing in patients with sepsis. Biochem Biophys Res Commun [Internet]. 2023 Nov 26;683(149079):149079. https://doi.org/10.1016/j.bbrc.2023.10.011</p>
<p>13. Grimm SL, Kaufman JT, Rice DP, Whittaker C, Bradshaw WJ, McLaren MR. Inferring the sensitivity of wastewater metagenomic sequencing for pathogen early detection [Internet]. bioRxiv. 2023. https://doi.org/10.1101/2023.12.22.23300450</p>
<p>14. Castillo DJ, Rifkin RF, Cowan DA, Potgieter M. The Healthy Human Blood Microbiome: Fact or Fiction? Front Cell Infect Microbiol [Internet]. 2019;9. https://doi.org/10.3389/fcimb.2019.00148</p>
<p>15. Spandole S, Cimponeriu D, Berca LM, Mihăescu G. Human anelloviruses: an update of molecular, epidemiological and clinical aspects. Arch Virol [Internet]. 2015 Apr 15 [cited 2025 Jan 8];160(4):893–908. https://doi.org/10.1007/s00705-015-2363-9</p>
<p>16. Sabbaghian M, Gheitasi H, Shekarchi AA, Tavakoli A, Poortahmasebi V. The mysterious anelloviruses: investigating its role in human diseases. BMC Microbiol [Internet]. 2024 Jan 29 [cited 2025 Jan 8];24(1):40. https://doi.org/10.1186/s12866-024-03187-7</p>
<p>17. Timmerman AL, Schönert ALM, van der Hoek L. Anelloviruses versus human immunity: how do we control these viruses? FEMS Microbiol Rev [Internet]. 2024 Jan 12 [cited 2025 Jan 8];48(1):fuae005. https://doi.org/10.1093/femsre/fuae005</p>
<p>18. Dunmire SK, Verghese PS, Balfour HH Jr.&nbsp;Primary Epstein-Barr virus infection. J Clin Virol [Internet]. 2018 May 1 [cited 2025 Jan 8];102:84–92. https://doi.org/10.1016/j.jcv.2018.03.001</p>
<p>19. Cannon MJ, Schmid DS, Hyde TB. Review of cytomegalovirus seroprevalence and demographic characteristics associated with infection: CMV seroprevalence. Rev Med Virol [Internet]. 2010 Jul 1 [cited 2025 Jan 8];20(4):202–13. https://doi.org/10.1002/rmv.655</p>
<p>20. Bodaghi S, Wood LV, Roby G, Ryder C, Steinberg SM, Zheng ZM. Could human papillomaviruses be spread through blood? J Clin Microbiol [Internet]. 2005 Nov [cited 2025 Jan 7];43(11):5428–34. https://doi.org/10.1128/JCM.43.11.5428-5434.2005</p>
<p>21. Cladel NM, Jiang P, Li JJ, Peng X, Cooper TK, Majerciak V, et al.&nbsp;Papillomavirus can be transmitted through the blood and produce infections in blood recipients: Evidence from two animal models. Emerg Microbes Infect [Internet]. 2019 Jul 25 [cited 2025 Jan 7];8(1):1108–21. https://doi.org/10.1080/22221751.2019.1637072</p>
<p>22. Boothpur R, Brennan DC. Human polyoma viruses and disease with emphasis on clinical BK and JC. J Clin Virol [Internet]. 2010 Apr 8 [cited 2025 Jan 7];47(4):306–12. https://doi.org/10.1016/j.jcv.2009.12.006</p>
<p>23. De Gascun CF, Carr MJ. Human polyomavirus reactivation: disease pathogenesis and treatment approaches. Clin Dev Immunol [Internet]. 2013 May 2 [cited 2025 Jan 7];2013:373579. https://doi.org/10.1155/2013/373579</p>
<p>24. Yang N, Dai R, Zhang X. Global prevalence of human pegivirus-1 in healthy volunteer blood donors: a systematic review and meta-analysis. Vox Sang [Internet]. 2020 Apr 1 [cited 2025 Jan 8];115(3):107–19. https://doi.org/10.1111/vox.12876</p>
<p>25. Hayden RT, Wolk DM, Carroll KC, Tang YW. Adenovirus. In: Diagnostic Microbiology of the Immunocompromised Host, Second Edition [Internet]. American Society of Microbiology; 2016 [cited 2025 Jan 9]. p.&nbsp;217–32. https://doi.org/10.1128/microbiolspec.dmih2-0020-2015</p>
<p>26. Cohen JI. Herpesvirus latency. J Clin Invest [Internet]. 2020 Jul 1 [cited 2025 Jan 6];130(7):3361–9. https://doi.org/10.1172/JCI136225</p>
<p>27. Griffiths P, Reeves M. Pathogenesis of human cytomegalovirus in the immunocompromised host. Nat Rev Microbiol [Internet]. 2021 Dec 24 [cited 2024 Jul 2];19(12):759–73. https://doi.org/10.1038/s41579-021-00582-z</p>
</section>
<section id="appendix-1:-dataset-descriptions" class="level1">
<h1>Appendix 1: Dataset descriptions</h1>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Study</th>
<th style="text-align: left;">Sample type</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cebrià-Mendoza et al.&nbsp;(3)</td>
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Study of the healthy human blood virome using DNA and RNA sequencing of pooled plasma from 587 healthy blood donors in Spain. Initial plasma collection method was not specified in the paper. Sample processing was optimized for viral enrichment: pooled samples were filtered (1.0 µM), centrifuged, and treated with nuclease to remove unprotected nucleic acids. The processed material was split into DNA and RNA fractions for separate extraction and sequencing.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thijssen et al.&nbsp;(4)</td>
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Analysis of blood virome differences between healthy donors and transfusion recipients in Iran. For our analysis, we used only samples from 100 healthy donors. Whole blood was collected and plasma was immediately separated, though separation method was not specified. Plasma was processed for viral enrichment through filtration (0.8 µm) and nuclease treatment. Samples were pooled, then DNA and RNA were jointly extracted, reverse transcribed, and randomly amplified before sequencing.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mengyi et al.&nbsp;(5)</td>
<td style="text-align: left;">Plasma</td>
<td style="text-align: left;">Characterization of the healthy blood virome using DNA sequencing of pooled plasma from 10,720 donors in China. Plasma was separated from whole blood collections via centrifugation. Plasma samples then underwent ultracentrifugation to concentrate viruses, microbes, and other material into a pellet. This pellet was resuspended and processed for DNA extraction and sequencing.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aydillo et al.&nbsp;(6)</td>
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">Analysis of 53 healthy U.S. participants (ages 18-39) in an influenza vaccine trial. Our analysis used only day 1 (pre-vaccination) samples. Total RNA was extracted from whole blood, and libraries were prepared using poly(A) enrichment and depletion of rRNA and <a href="https://en.wikipedia.org/wiki/Globin">globin</a> RNA.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O’Connell (7)</td>
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">Study of 138 U.S. emergency department patients with chronic conditions (including HIV/AIDS, viral hepatitis, heart disease, diabetes, and cancers). Total RNA was extracted from whole blood using <a href="https://en.wikipedia.org/wiki/Spin_column-based_nucleic_acid_purification">spin column-based solid phase extraction</a>, followed by depletion of ribosomal and globin RNA before sequencing.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thompson et al.&nbsp;(8)</td>
<td style="text-align: left;">Whole blood</td>
<td style="text-align: left;">Analysis of 417 U.S. individuals (353 COVID-19 patients and 64 healthy controls), using baseline (day 0) samples only. Total RNA was extracted from whole blood using magnetic beads, with depletion of ribosomal, globin, and mitochondrial RNA before sequencing.</td>
</tr>
</tbody>
</table>
<p><strong>Table A1.1</strong>: Dataset descriptions</p>
</section>
<section id="appendix-2:-human-infecting-virus-genera" class="level1">
<h1>Appendix 2: Human-infecting virus genera</h1>
<p><img src="../img/2025-01-31_figureA2.png" class="img-fluid" alt="hv-genera"> <strong>Figure A2</strong>: Human-infecting virus genera variation across samples in each dataset. Left: Percentage of samples in each dataset that have reads from the human-infecting genera. Right: Relative abundance of human-infecting genera in each dataset (filtered for genera found in &gt;5 samples).</p>


<!-- -->

</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>In this context, “healthy” refers to individuals without severe medical conditions or symptoms recruited for studies as “healthy” controls. Such individuals may still harbor asymptomatic viral infections, which are common in the general population.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>While we originally set out to collect data from only healthy donors, it became clear that finding datasets was going to be harder than we expected, so we decided to include data from additional donors, even if they were symptomatic.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Removing reads that were unclassified by Kraken2 reduces putative HV reads by around a factor of 3, with a larger effect on plasma studies (particularly that of Mengyi et al.&nbsp;(5)). This drop-off may indicate a large presence of human viruses that are not represented in RefSeq and are thereby left out of our analysis. Characterization of these reads is a fruitful area for future analysis.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>While the absence of <em>Orthoherpesviridae</em> likely reflects methodological differences given their high prevalence in human populations, the absence of <em>Retroviridae</em> could simply reflect differences in donor populations, as retroviruses are less prevalent.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Exploring Blood-Based Biosurveillance, Part 3: The Blood Virome"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">  - Harmon Bhasin</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">  - Michael McLaren</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  - Lennart Justen</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2025-02-03</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="an">toc:</span><span class="co"> true</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"> html:</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="co">   code-fold: true</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co">   code-tools: true</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">   code-link: true</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">   df-print: paged</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> visual</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">title-block-banner:</span><span class="co"> black</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>*This is the third post in a series of blogs exploring blood-based biosurveillance for novel pathogen detection as part of the NAO’s effort to [evaluate different biosurveillance](https://naobservatory.org/evaluating-biosurveillance-approaches) approaches. We once again thank our colleagues at the NAO, particularly Jeff Kaufman and Will Bradshaw, for their valuable feedback.*</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu"># Summary</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>To help assess the effectiveness of blood-based biosurveillance, we reanalyzed six publicly available whole blood and plasma metagenomic sequencing datasets, examining both kingdom-level composition and the prevalence and relative abundance of human-infecting viruses (HVs). These studies represent diverse sample processing methods, donor populations, and sequencing approaches. Our analysis revealed that sample type and processing methods can strongly influence viral detection. Plasma samples consistently showed higher total HV relative abundance than whole blood, particularly when employing additional filtration to remove human nucleic acid, though this step may reduce detection of primarily intracellular viruses.</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>*Anelloviridae* was the most consistently detected viral family, appearing in most datasets with particularly high prevalence in plasma samples. We also detected viral families associated with intracellular latent infections, including *Orthoherpesviridae* and *Retroviridae*. These findings align well with known epidemiology of blood-borne and latent viral infections. Common respiratory viruses were largely absent, suggesting that a biosurveillance system aiming for coverage of the full range of human viruses will need to combine multiple sample types.</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu"># Introduction</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>Untargeted metagenomic sequencing (MGS) of blood-derived samples could enable greatly improved early detection of novel viral threats. In our previous posts, we examined the <span class="co">[</span><span class="ot">biological characteristics</span><span class="co">](https://naobservatory.org/blog/exploring-blood-biosurveillance-part1)</span> of blood and identified <span class="co">[</span><span class="ot">promising strategies</span><span class="co">](https://naobservatory.org/blog/exploring-blood-biosurveillance-part2)</span> for accessing samples in high-throughput from the U.S. blood supply system. In this post we investigate the human blood virome by reanalyzing a diverse set of MGS datasets to better understand pathogen presence and relative abundance (RA) – key metrics for determining the sensitivity, cost, and robustness of any future blood-based biosurveillance system.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>We reanalyze six publicly available MGS datasets, drawn from both whole blood and plasma. We apply a consistent computational pipeline to characterize the blood virome, examining the RA and prevalence of human-infecting viruses (HV) across studies with distinct sample types, sample processing methods, and donor populations. Our findings help quantify the potential role of blood-based surveillance within a broader system for detecting emerging pathogens, complementing existing approaches like wastewater and respiratory swab sampling.</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="fu"># The MGS datasets</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>We sought MGS data to characterize the blood virome of healthy donor populations<span class="ot">[^1]</span> that could represent eligible blood and plasma donors, looking for three datasets for each sample type (whole blood and plasma). After an initial literature review, we excluded a number of suitable studies due to the lack of publicly available data (1) or the requirement of onboarding procedures to access the data (2). We ultimately relaxed the requirement for data strictly from healthy donors and selected six publicly accessible, short read Illumina MGS datasets to re-analyze (Table 1).</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="ot">[^1]: </span>In this context, "healthy" refers to individuals without severe medical conditions or symptoms recruited for studies as “healthy” controls. Such individuals may still harbor asymptomatic viral infections, which are common in the general population.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>| Study | Sample type | Country† | Donor description | Samples (Contributing individuals) | Total read pairs (Avg. per sample) | Sample prep optimization for viruses? | Nucleic acid sequenced | Read type |</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>| Cebriá-Mendoza et al. (3) | Plasma | Spain | Healthy | 60 (587) | 230M (3.8M) | Yes | DNA+RNA | 2x150 bp |</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>| Thijssen et al. (4) | Plasma | Iran | Healthy | 21 (100) | 116M(5.6M) | Yes | DNA+RNA | 2x150 bp |</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>| Mengyi et al. (5) | Plasma | China | Healthy | 201 (≤10,720††) | 3.4B(17.1M) | No | DNA | 2x150 bp |</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>| Aydillo et al. (6) | Whole blood | USA | Healthy | 53 | 1.7B (32.8M) | No | RNA | 2x100 bp |</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>| O’Connell (7) | Whole blood | USA | Emergency room patients with chronic health condition | 138 | 3.1B (22.5M) | No | RNA | 2x150 bp |</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>| Thompson et al. (8) | Whole blood | USA | Hospitalized COVID-19 patients and healthy controls<span class="ot">[^2]</span> | 417 | 27.7B (66.4M) | No | RNA | 2x100 bp |</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a><span class="ot">[^2]: </span>While we originally set out to collect data from only healthy donors, it became clear that finding datasets was going to be harder than we expected, so we decided to include data from additional donors, even if they were symptomatic.</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>**Table 1**: Key characteristics of the six metagenomic sequencing datasets analyzed in this study. Numbers in parentheses indicate total donors contributing to pooled samples. Datasets are ordered by increasing percentage of human reads (see Table 2). Detailed descriptions of each study available in <span class="co">[</span><span class="ot">Appendix 1</span><span class="co">](#appendix-1:-dataset-descriptions)</span>. †: Country denotes countries where the donations occurred. ††: The total number of donations that contributed to all samples is 10,720; the authors do not state whether some individuals contributed multiple donations.</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>The datasets included were originally generated for a variety of purposes, ranging from characterizing the healthy human blood virome (3–5) to studying host responses during vaccination (6), evaluating biomarkers for chronic conditions (7), and investigating molecular signatures of long COVID (8). As a result, these studies exhibit substantial methodological differences that complicate direct comparisons between plasma and whole blood as sample types.</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Donor population:** The plasma studies analyzed samples from healthy donors across different countries, with all studies using pooled samples from multiple donors within the same region. In contrast, the whole blood studies analyzed individual (unpooled) samples from both healthy and ill participants exclusively within the U.S.</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Sample processing:** The plasma studies had varying levels of sample processing to remove human cellular material. While the methods used to separate plasma from whole blood in Cebrià-Mendozá et al. (3) and Thijssen et al. (4) were not specified, both studies employed additional viral enrichment protocols on their plasma samples, including filtration of remaining host cells (1.0 μm and 0.8 μm respectively) and nuclease treatment of unprotected nucleic acids. In contrast, Mengyi et al. (5) separated plasma from whole blood using centrifugation and employed an additional ultracentrifugation step to concentrate viruses and other material into a pellet, without filtration or nuclease treatment steps. The whole blood studies used standard RNA sequencing protocols focused on host transcriptomics, with cell lysis, RNA extraction, and depletion of ribosomal and <span class="co">[</span><span class="ot">globin</span><span class="co">](https://en.wikipedia.org/wiki/Globin)</span> RNA.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span>**Sequencing approach:** Whole blood studies using RNA sequencing exclusively at higher depth (average reads/sample ranging from 22-66M), while plasma studies used either DNA sequencing alone or combined DNA/RNA approaches at lower depth (average reads/sample ranging from 3-17M). While RNA-only studies can still detect DNA viruses through their transcripts, and DNA studies can capture some RNA viruses through reverse-transcribed DNA intermediates, the nucleic acid type sequenced is certain to impact detection sensitivity of different viral families.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>These differences in sample preparation, donor population, and sequencing approach make it challenging to isolate the effects of sample type on taxonomic composition. Some studies have more successfully controlled for these variables in direct comparisons of whole blood and plasma (9–12), though their underlying data is often restricted. Nevertheless, analyzing these diverse datasets through a single computational pipeline allows us to observe consistent trends and assess variation across methodologies. Further relevant details on the studies are described in <span class="co">[</span><span class="ot">Appendix 1</span><span class="co">](#appendix-1:-dataset-descriptions)</span>.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="fu"># Computational methods</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a>We processed all datasets through a modified version of the viral metagenomic sequencing pipeline (<span class="co">[</span><span class="ot">v2.2.1</span><span class="co">](https://github.com/harmonbhasin/mgs-workflow)</span>) described in Grimm et al. (13). To reduce computational requirements, we simplified the adapter trimming steps by using only FASTP rather than the original combination of FASTP, Cutadapt, and Trimmomatic. </span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>The pipeline consists of two workflows: the taxonomic profiling workflow and the viral identification workflow. The taxonomic profiling workflow uses Kraken2 to assign reads to the least common ancestor (based on NCBI taxonomy) of matched genomes in the Kraken2 Standard database, which includes RefSeq prokaryotic, viral, and vector genomes along with the human genome. Results from this workflow determine the kingdom-level composition shown in Table 1<span class="sc">\.</span> Since the database lacks non-human eukaryotic reference genomes, reads from such organisms are expected to remain unassigned.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>The viral-identification workflow maps reads with Kraken2 (also with the Standard database) and aligns reads using Bowtie2 to an expanded database of human-infecting virus genomes from GenBank, reporting putative human-infecting virus reads based on the condition that the read aligns by Bowtie2 to a human virus and is not mapped by Kraken2 to a taxon that is not a human virus. We use the Bowtie2 assignment as the taxonomic assignment of a read.<span class="ot">[^3]</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>We applied additional filtering to taxonomic assignments in our downstream analysis. First, we removed reads from the Cebrià-Mendoza et al. (3) dataset that Kraken2 assigned to *Microviridae* or *Rhabdoviridae* families, which originated from Phi-X and Vesicular Stomatitis Virus spike-in controls. Second, we removed SARS-CoV-2 reads from the Thijssen et al. (4) and Mengyi et al. (5), as these were likely laboratory contaminants given that samples were collected before the COVID-19 pandemic (2012-2018).</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>Complete analysis code and documentation are available in our public GitHub <span class="co">[</span><span class="ot">repository</span><span class="co">](https://github.com/naobservatory/blood-blog-post-3)</span>.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="ot">[^3]:  </span>Removing reads that were unclassified by Kraken2 reduces putative HV reads by around a factor of 3, with a larger effect on plasma studies (particularly that of Mengyi et al. (5)). This drop-off may indicate a large presence of human viruses that are not represented in RefSeq and are thereby left out of our analysis. Characterization of these reads is a fruitful area for future analysis.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="fu"># Kingdom-level composition</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a>| Sample type | Dataset | Unassigned | Human | Bacterial | Archaeal† | Viral |</span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>|:----------|:----------|:----------|:----------|:----------|:----------|:----------|</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a>| Plasma | Cebrià-Mendoza et al. (3) | 43% | 2.0% | 51% | 0.034% | 4.7% |</span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a>| Plasma | Thijssen et al. (4) | 73% | 22% | 4.5% | 0.013% | 0.034% |</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a>| Plasma | Mengyi et al. (5) | 1.3% | 98.4% | 0.27% | 0.00096% | 0.013% |</span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>| Whole blood | Aydillo et al. (6) | 0.35% | 99.54% | 0.11% | 0.00061% | 0.00028% |</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>| Whole blood | O’Connell (7) | 0.087% | 99.86% | 0.050% | 0.000038% | 0.00011% |</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>| Whole blood | Thompson et al. (8) | 0.11% | 99.87% | 0.013% | 0.000074% | 0.00027% |</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>**Table 2**: Kingdom-level taxonomic composition showing percentage of reads assigned to each kingdom after random subsampling to 1 million read pairs per sample. †: Archaea are generally not expected in human blood (14); these reads may represent laboratory contamination or misassignment during taxonomic classification.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>Datasets varied substantially in kingdom composition (Table 2). Whole blood datasets showed remarkable consistency, with human reads exceeding 99.5% of sequences and minimal variation in non-eukaryotic kingdoms. In contrast, plasma datasets exhibited greater heterogeneity. Two plasma studies (3,4) that enriched for viruses by filtering out eukaryotic cells showed lower human relative abundance (RA) and higher non-eukaryotic kingdom RA. The third plasma study (5), which only concentrated samples via ultracentrifugation without filtration, showed intermediate values. Even without enrichment, plasma datasets consistently contained a greater fraction of non-human sequences than whole blood, with the viral fraction in Mengyi et al. (5) exceeding whole blood datasets by two orders of magnitude.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>The kingdom-level composition indicates that both sample type and sample processing methods have a substantial effect on human RA, with lower human RA corresponding to significantly higher viral RA. Plasma should inherently contain less human nucleic acid than whole blood due to its cell-free nature, though depending on the initial state of the plasma it seems this advantage can be further enhanced through a filtration step.</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="fu"># Human-infecting viruses</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="al">![hv-dataset](/img/2025-01-31_figure1.png)</span> **Figure 1**: Distribution of human-infecting virus relative abundance across all samples in six studies. Each point represents a single sample. Boxplots show the distribution including samples with zero HV reads (box: 25th-75th percentiles, line: median, whiskers: extend to 1.5× interquartile range). For studies with many zeros, the median and potentially the entire boxplot may collapse to zero. Numbers underneath the study names denote the percentage of samples with at least one HV read.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>Total human-infecting virus (HV) RA differed markedly between studies (Figure 1) in a manner consistent with the kingdom-level composition. Datasets that had lower human RA tended to have more samples with HV reads and higher total-HV RA in those samples. Whole blood samples generally showed low HV RA, with a maximum of 1.35×10^(-4) across all samples and with the majority of samples in each dataset containing no HV reads. Plasma samples showed higher RA, with median values ranging from 10^(-6) to 10^(-2) across studies and only a small fraction of samples containing no HV reads. Cebriá-Mendoza et al. (3) had the highest median RA of 6.06×10^(-3) consistent with their success in removing human nucleic acids during sample processing.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>Across datasets, the presence and RA of total HVs increased inversely to the fraction of human reads in the dataset, suggesting that presence and RA of HVs is driven by the ability for a given sample type and processing protocol to yield non-human reads. The higher proportion of samples with HV reads in plasma datasets also likely reflects the use of pooled samples, which increases the chance that an HV will be present in the sample.</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="al">![hv-composition](/img/2025-01-31_figure2.png)</span> **Figure 2**: Distribution of human-infecting virus families across datasets, showing the average relative abundance of each viral family per dataset. Families contributing less than 5% to any single dataset are grouped into the "Other" category.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>To understand the viral composition across datasets, we analyzed which virus families contributed to the human-infecting virus (HV) reads (Figure 2). We found substantial variation in the dominant viral families, both between and within sample types. In the two plasma studies that used filtration to enrich for viral nucleic acids (3,4), <span class="co">[</span><span class="ot">*Anelloviridae*</span><span class="co">](https://en.wikipedia.org/wiki/Anelloviridae)</span> was the most prevalent family. In the third plasma study (5)*, Parvoviridae* was the most abundant. Among whole blood studies, [*Flaviviridae*](https://en.wikipedia.org/wiki/Flaviviridae) dominated in two datasets (6,8) but was notably absent in the third (7). The substantial heterogeneity in the taxonomic composition of HV reads appears to only be partly explained by sample type, with other factors such as sample preparation, sequencing depth, and donor population profile likely accounting for further differences.</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a><span class="al">![hv-ra-prev](/img/2025-01-31_figure3.png)</span> **Figure 3**: Detection of human-infecting virus (HV) families across whole blood and plasma datasets, including only families found in at least five samples. Left panel: Prevalence of each viral family, shown as the percentage of samples containing at least one viral read. Right panel: Relative abundance of viral families in positive samples.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>Our analysis identified 16 human virus (HV) families across all datasets, with 10 families detected in at least five samples (Figure 3). The relative abundance (RA) of detected viruses varied widely, ranging from 10^(-8) to 10^(-1). Whole blood samples generally showed lower non-zero RA values, partly due to their greater sequencing depth (Table 1) which enables detection of rarer sequences.</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>*​​Anelloviridae* emerged as the most consistently detected family, appearing in five of six datasets with particularly high prevalence (<span class="sc">\&gt;</span>75%) in plasma samples. Their relative abundance showed substantial variation, spanning up to three orders of magnitude within individual datasets. This high prevalence aligns with current understanding—Anelloviruses are nearly ubiquitous in humans, maintain persistent replication in T lymphocytes, and produce an estimated 10^(10) virions daily (15–17).</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>We detected several viral families known to establish persistent infections in humans. <span class="co">[</span><span class="ot">*Retroviridae*</span><span class="co">](https://en.wikipedia.org/wiki/Retrovirus)</span> and <span class="co">[</span><span class="ot">*Orthoherpesviridae*</span><span class="co">](https://en.wikipedia.org/wiki/Herpesviridae)</span> were found across multiple datasets, consistent with their high prevalence in human populations. The detected *Orthoherpesviridae* genera ([Appendix 2](#appendix-2:-human-infecting-virus-genera)) correspond to common herpesviruses such as HSV-1/2, Epstein-Barr virus (EBV; infecting \~90% of adults worldwide), and human cytomegalovirus (HCMV; \~80% prevalence) (18,19). Within *Retroviridae*, we identified sequences from the *Lentivirus* genus, which includes HIV.</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>Other persistent viral families detected include <span class="co">[</span><span class="ot">*Papillomaviridae*</span><span class="co">](https://en.wikipedia.org/wiki/Papillomaviridae)</span>, <span class="co">[</span><span class="ot">*Polyomaviridae*</span><span class="co">](https://en.wikipedia.org/wiki/Polyomaviridae)</span>, and <span class="co">[</span><span class="ot">*Flaviviridae*</span><span class="co">](https://en.wikipedia.org/wiki/Flaviviridae)</span>. *Papillomaviridae* sequences appeared at low prevalence (\&lt;10%) in both sample types, likely reflecting either human papillomavirus (HPV) persistence in blood cells or shedding from infected tissues (20,21). The *Polyomaviridae* family, containing human polyomaviruses which are widespread (\~80% prevalence among adults; (22)) and primarily asymptomatic, was also detected in both blood and plasma. Polyomaviruses can replicate at low levels within lymphocytes and persist in bone marrow or kidneys (23). *Flaviviridae*, represented primarily by human pegivirus (<span class="co">[</span><span class="ot">Appendix 2</span><span class="co">](#appendix-2:-human-infecting-virus-genera)</span>), appeared in more than 25% of samples in Cebriá-Mendoza et al. (3). This lymphocyte-infecting virus is non-pathogenic, with prevalence estimates ranging from 1.7% in North America to 9.1% in South America (24).</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>Absent from both whole blood and plasma samples were viral families like *Picornaviridae* (including rhinoviruses) and *Orthomyxoviridae* (including influenza viruses) responsible for common respiratory infections. This is consistent with our [previous investigation](https://naobservatory.org/blog/exploring-blood-biosurveillance-part1) which found that these viruses typically appear in blood only during severe infections. The sole exception was [*Coronaviridae*](https://en.wikipedia.org/wiki/Coronaviridae) (including coronaviruses) in the Thompson et al. (8) dataset, which specifically included hospitalized COVID-19 patients. While we detected [*Adenoviridae*](https://en.wikipedia.org/wiki/Adenoviridae), a family of viruses that can cause respiratory illness, these viruses have broader tissue tropism and can establish lymphocyte latency (25), distinguishing them from typical respiratory pathogens.</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>Sample processing methods appear to have significantly influenced viral detection patterns. Plasma studies using filtration to remove eukaryotic cells (3,4) achieved the highest relative abundances for HV reads (Figure 1), particularly *Anelloviridae*. However, these filtered plasma studies missed virus families like *Retroviridae* and *Orthoherpesviridae* that were detected in studies retaining more human nucleic acid content[^4] – namely the whole blood studies and Mengyi et al. (5), a plasma study which did not employ filtering of eukaryotic cells. Mengyi et al. (5) showed an intermediate pattern overall, with lower *Anelloviridae* abundance than filtered plasma studies but higher than whole blood studies, while still detecting *Orthoherpesviridae* and *Retroviridae*.</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a><span class="ot">[^4]: </span>While the absence of *Orthoherpesviridae* likely reflects methodological differences given their high prevalence in human populations, the absence of *Retroviridae* could simply reflect differences in donor populations, as retroviruses are less prevalent.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>The varying detection patterns observed for the *Retroviridae* and *Orthoherpesviridae* families align with their biological characteristics, with possible implications for blood-based biosurveillance. These viral families establish long-term intracellular latent infections through distinct mechanisms – retroviruses integrate into the host genome as <span class="co">[</span><span class="ot">proviral</span><span class="co">](https://en.wikipedia.org/wiki/Provirus)</span> DNA, while herpesviruses persist as nuclear <span class="co">[</span><span class="ot">episomes</span><span class="co">](https://en.wikipedia.org/wiki/Episome)</span> (viral plasmids in the nucleus). Their detection in both whole blood and unfiltered plasma samples indicates that preserving material from within human cells is critical for detecting viruses in predominantly intracellular states. Whole blood samples provide the most reliable source of intracellular content, as plasma samples may vary substantially in their cellular content depending on collection methods and pre-processing done before samples are received.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>However, detecting viruses in intracellular states may be less critical for early warning of novel emerging pathogens. During initial infection and active spread, blood-borne pathogens would likely be present in plasma regardless of their ultimate cellular tropism, as viruses must pass through the extracellular space to establish and spread their infection. Even latent viruses periodically reactivate with associated viral shedding into plasma (26,27). These biological patterns suggest that filtered plasma samples could effectively capture novel blood-borne pathogens while benefiting from the greater viral sensitivity associated with removing human nucleic acid content.</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a><span class="fu"># Discussion</span></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>Our reanalysis of six publicly available MGS datasets provides new insights into the potential utility of blood-based biosurveillance. Sample type and processing methods strongly influence viral detection—plasma samples consistently showed higher viral relative abundance than whole blood, and viral enrichment through filtration further improved detection of some viral families. However, this enhanced sensitivity through filtration appears to come with tradeoffs, potentially reducing detection of primarily intracellular viruses like *Orthoherpesviridae* and *Retroviridae*.</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>The detected viruses align well with known epidemiology of blood-borne and latent viral infections, suggesting MGS of blood and plasma can reliably detect an important subset of human-infecting viruses. However, common respiratory and gastrointestinal viruses were notably absent from samples from healthy donors, indicating that blood-based surveillance may be most effective as part of a complementary system incorporating other sample types like respiratory swabs and wastewater.</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a>Several limitations of our analysis suggest directions for future work. Contamination is a significant concern in metagenomic sequencing studies, as outside nucleic acid can be introduced during sample collection, processing, and library preparation, altering the taxonomic profile and potentially leading to false positive detections. A more rigorous analysis of potential contamination, including examining control samples and systematic removal of laboratory contaminants, would strengthen confidence in our viral detections. Additionally, our ability to causally assign the differences in viral presence and abundance to sample type and viral enrichment is limited by the differences among studies in donor population and other differences in sample processing and sequencing methods. Statistical modeling that accounts for both sequencing depth and expected viral prevalence in donor populations could provide estimates of detection sensitivity for a given cost or amount of sequencing (13). However, obtaining accurate estimates of viral prevalence is challenging. Studies directly comparing whole blood and plasma fractions from the same individuals using the same sequencing method would enable more definitive conclusions about sample type differences, as they would allow us to eliminate variation in viral prevalence and sequencing protocol.</span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>Our work has shown that blood captures a considerable diversity of human-infecting viruses and that sample type and processing methods greatly impact viral relative abundance. The results suggest that if the sample collection and processing was optimized, blood could provide sensitive detection of pathogens not readily detectable in wastewater or nasal swabs. Overall, we’re excited about the role that blood-based biosurveillance could play in our broader early detection network and are interested in hearing about potential partners in this space.</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a><span class="fu"># References</span></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a>1<span class="sc">\.</span> Moustafa A, Xie C, Kirkness E, Biggs W, Wong E, Turpaz Y, et al. The blood DNA virome in 8,000 humans. PLoS Pathog <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2017 Mar 22;13(3):e1006292. https://doi.org/10.1371/journal.ppat.1006292</span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>2<span class="sc">\.</span> Tan CCS, Ko KKK, Chen H, Liu J, Loh M, Chia M, et al. No evidence for a common blood microbiome based on a population study of 9,770 healthy humans. Nature Microbiology <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2023 May;8(5):973–85. https://doi.org/10.1038/s41564-023-01350-w</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>3<span class="sc">\.</span> Cebriá-Mendoza M, Bracho MA, Arbona C, Larrea L, Díaz W, Sanjuán R, et al. Exploring the Diversity of the Human Blood Virome. Viruses <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2021 Nov 21;13(11). https://doi.org/10.3390/v13112322</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>4<span class="sc">\.</span> Thijssen M, Khamisipour G, Maleki M, Devos T, Li G, Van Ranst M, et al. Characterization of the Human Blood Virome in Iranian Multiple Transfused Patients. Viruses <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2023 Jun 23;15(7). https://doi.org/10.3390/v15071425</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>5<span class="sc">\.</span> Mengyi Z, Yuhui L, Zhan G, Anqing L, Yujia L, Shilin L, et al. Plasma metagenomics reveals regional variations of emerging and re-emerging pathogens in Chinese blood donors with an emphasis on human parvovirus B19. One Health <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2023 Dec;17:100602. https://doi.org/10.1016/j.onehlt.2023.100602</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a>6<span class="sc">\.</span> Aydillo T, Gonzalez-Reiche AS, Stadlbauer D, Amper MA, Nair VD, Mariottini C, et al. Transcriptome signatures preceding the induction of anti-stalk antibodies elicited after universal influenza vaccination. NPJ Vaccines <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2022 Dec 10 <span class="sc">\[</span>cited 2024 Oct 9<span class="sc">\]</span>;7(1):160. https://doi.org/10.1038/s41541-022-00583-w</span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>7<span class="sc">\.</span> O’Connell GC. Dataset including whole blood gene expression profiles and matched leukocyte counts with utility for benchmarking cellular deconvolution pipelines. BMC Genom Data <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2024 May 7 <span class="sc">\[</span>cited 2024 Oct 9<span class="sc">\]</span>;25(1):45. https://doi.org/10.1186/s12863-024-01223-z</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>8<span class="sc">\.</span> Thompson RC, Simons NW, Wilkins L, Cheng E, Del Valle DM, Hoffman GE, et al. Molecular states during acute COVID-19 reveal distinct etiologies of long-term sequelae. Nat Med <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2023 Jan <span class="sc">\[</span>cited 2024 Oct 9<span class="sc">\]</span>;29(1):236–46. https://doi.org/10.1038/s41591-022-02107-4</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>9<span class="sc">\.</span> Flurin L, Wolf MJ, Fisher CR, Cano Cevallos EJ, Vaillant JJ, Pritt BS, et al. Pathogen Detection in Infective Endocarditis Using Targeted Metagenomics on Whole Blood and Plasma: a Prospective Pilot Study. Simner PJ, editor. J Clin Microbiol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2022 Sep 21;60(9). https://doi.org/10.1128/jcm.00621-22</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>10<span class="sc">\.</span> Lau P, Cordey S, Brito F, Tirefort D, Petty TJ, Turin L, et al. Metagenomics analysis of red blood cell and fresh-frozen plasma units. Transfusion <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2017 Jul;57(7):1787–800. https://doi.org/10.1111/trf.14148</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>11<span class="sc">\.</span> Wang D, Zhang Z, Shen H, Jin F, Liang J, Shen D, et al. Comparison of plasma and blood cell samples in metagenomic next-generation sequencing for identification of the causative pathogens of fever. Heliyon <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2024 Jun;10(11):e31677. https://doi.org/10.1016/j.heliyon.2024.e31677</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>12<span class="sc">\.</span> Wu C, Yu X, Gai W, Liu Y, Qi Y, Zheng Y, et al. Diagnostic value of plasma and blood cells metagenomic next-generation sequencing in patients with sepsis. Biochem Biophys Res Commun <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2023 Nov 26;683(149079):149079. https://doi.org/10.1016/j.bbrc.2023.10.011</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>13<span class="sc">\.</span> Grimm SL, Kaufman JT, Rice DP, Whittaker C, Bradshaw WJ, McLaren MR. Inferring the sensitivity of wastewater metagenomic sequencing for pathogen early detection <span class="sc">\[</span>Internet<span class="sc">\]</span>. bioRxiv. 2023. https://doi.org/10.1101/2023.12.22.23300450</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a>14<span class="sc">\.</span> Castillo DJ, Rifkin RF, Cowan DA, Potgieter M. The Healthy Human Blood Microbiome: Fact or Fiction? Front Cell Infect Microbiol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2019;9. https://doi.org/10.3389/fcimb.2019.00148</span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>15<span class="sc">\.</span> Spandole S, Cimponeriu D, Berca LM, Mihăescu G. Human anelloviruses: an update of molecular, epidemiological and clinical aspects. Arch Virol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2015 Apr 15 <span class="sc">\[</span>cited 2025 Jan 8<span class="sc">\]</span>;160(4):893–908. https://doi.org/10.1007/s00705-015-2363-9</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>16<span class="sc">\.</span> Sabbaghian M, Gheitasi H, Shekarchi AA, Tavakoli A, Poortahmasebi V. The mysterious anelloviruses: investigating its role in human diseases. BMC Microbiol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2024 Jan 29 <span class="sc">\[</span>cited 2025 Jan 8<span class="sc">\]</span>;24(1):40. https://doi.org/10.1186/s12866-024-03187-7</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>17<span class="sc">\.</span> Timmerman AL, Schönert ALM, van der Hoek L. Anelloviruses versus human immunity: how do we control these viruses? FEMS Microbiol Rev <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2024 Jan 12 <span class="sc">\[</span>cited 2025 Jan 8<span class="sc">\]</span>;48(1):fuae005. https://doi.org/10.1093/femsre/fuae005</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>18<span class="sc">\.</span> Dunmire SK, Verghese PS, Balfour HH Jr. Primary Epstein-Barr virus infection. J Clin Virol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2018 May 1 <span class="sc">\[</span>cited 2025 Jan 8<span class="sc">\]</span>;102:84–92. https://doi.org/10.1016/j.jcv.2018.03.001</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>19<span class="sc">\.</span> Cannon MJ, Schmid DS, Hyde TB. Review of cytomegalovirus seroprevalence and demographic characteristics associated with infection: CMV seroprevalence. Rev Med Virol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2010 Jul 1 <span class="sc">\[</span>cited 2025 Jan 8<span class="sc">\]</span>;20(4):202–13. https://doi.org/10.1002/rmv.655 </span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a>20<span class="sc">\.</span> Bodaghi S, Wood LV, Roby G, Ryder C, Steinberg SM, Zheng ZM. Could human papillomaviruses be spread through blood? J Clin Microbiol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2005 Nov <span class="sc">\[</span>cited 2025 Jan 7<span class="sc">\]</span>;43(11):5428–34. https://doi.org/10.1128/JCM.43.11.5428-5434.2005</span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a>21<span class="sc">\.</span> Cladel NM, Jiang P, Li JJ, Peng X, Cooper TK, Majerciak V, et al. Papillomavirus can be transmitted through the blood and produce infections in blood recipients: Evidence from two animal models. Emerg Microbes Infect <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2019 Jul 25 <span class="sc">\[</span>cited 2025 Jan 7<span class="sc">\]</span>;8(1):1108–21. https://doi.org/10.1080/22221751.2019.1637072</span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>22<span class="sc">\.</span> Boothpur R, Brennan DC. Human polyoma viruses and disease with emphasis on clinical BK and JC. J Clin Virol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2010 Apr 8 <span class="sc">\[</span>cited 2025 Jan 7<span class="sc">\]</span>;47(4):306–12. https://doi.org/10.1016/j.jcv.2009.12.006</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>23<span class="sc">\.</span> De Gascun CF, Carr MJ. Human polyomavirus reactivation: disease pathogenesis and treatment approaches. Clin Dev Immunol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2013 May 2 <span class="sc">\[</span>cited 2025 Jan 7<span class="sc">\]</span>;2013:373579. https://doi.org/10.1155/2013/373579</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>24<span class="sc">\.</span> Yang N, Dai R, Zhang X. Global prevalence of human pegivirus-1 in healthy volunteer blood donors: a systematic review and meta-analysis. Vox Sang <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2020 Apr 1 <span class="sc">\[</span>cited 2025 Jan 8<span class="sc">\]</span>;115(3):107–19. https://doi.org/10.1111/vox.12876</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>25<span class="sc">\.</span> Hayden RT, Wolk DM, Carroll KC, Tang YW. Adenovirus. In: Diagnostic Microbiology of the Immunocompromised Host, Second Edition <span class="sc">\[</span>Internet<span class="sc">\]</span>. American Society of Microbiology; 2016 <span class="sc">\[</span>cited 2025 Jan 9<span class="sc">\]</span>. p. 217–32. https://doi.org/10.1128/microbiolspec.dmih2-0020-2015</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>26<span class="sc">\.</span> Cohen JI. Herpesvirus latency. J Clin Invest <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2020 Jul 1 <span class="sc">\[</span>cited 2025 Jan 6<span class="sc">\]</span>;130(7):3361–9. https://doi.org/10.1172/JCI136225</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>27<span class="sc">\.</span> Griffiths P, Reeves M. Pathogenesis of human cytomegalovirus in the immunocompromised host. Nat Rev Microbiol <span class="sc">\[</span>Internet<span class="sc">\]</span>. 2021 Dec 24 <span class="sc">\[</span>cited 2024 Jul 2<span class="sc">\]</span>;19(12):759–73. https://doi.org/10.1038/s41579-021-00582-z</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a><span class="fu"># Appendix 1: Dataset descriptions {#appendix-1:-dataset-descriptions}</span></span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>| Study | Sample type | Description |</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>|:-----------------------|:-----------------------|:-----------------------|</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>| Cebrià-Mendoza et al. (3) | Plasma | Study of the healthy human blood virome using DNA and RNA sequencing of pooled plasma from 587 healthy blood donors in Spain. Initial plasma collection method was not specified in the paper. Sample processing was optimized for viral enrichment: pooled samples were filtered (1.0 µM), centrifuged, and treated with nuclease to remove unprotected nucleic acids. The processed material was split into DNA and RNA fractions for separate extraction and sequencing. |</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>| Thijssen et al. (4) | Plasma | Analysis of blood virome differences between healthy donors and transfusion recipients in Iran. For our analysis, we used only samples from 100 healthy donors. Whole blood was collected and plasma was immediately separated, though separation method was not specified. Plasma was processed for viral enrichment through filtration (0.8 µm) and nuclease treatment. Samples were pooled, then DNA and RNA were jointly extracted, reverse transcribed, and randomly amplified before sequencing. |</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>| Mengyi et al. (5) | Plasma | Characterization of the healthy blood virome using DNA sequencing of pooled plasma from 10,720 donors in China. Plasma was separated from whole blood collections via centrifugation. Plasma samples then underwent ultracentrifugation to concentrate viruses, microbes, and other material into a pellet. This pellet was resuspended and processed for DNA extraction and sequencing. |</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>| Aydillo et al. (6) | Whole blood | Analysis of 53 healthy U.S. participants (ages 18-39) in an influenza vaccine trial. Our analysis used only day 1 (pre-vaccination) samples. Total RNA was extracted from whole blood, and libraries were prepared using poly(A) enrichment and depletion of rRNA and <span class="co">[</span><span class="ot">globin</span><span class="co">](https://en.wikipedia.org/wiki/Globin)</span> RNA. |</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>| O’Connell (7) | Whole blood | Study of 138 U.S. emergency department patients with chronic conditions (including HIV/AIDS, viral hepatitis, heart disease, diabetes, and cancers). Total RNA was extracted from whole blood using <span class="co">[</span><span class="ot">spin column-based solid phase extraction</span><span class="co">](https://en.wikipedia.org/wiki/Spin_column-based_nucleic_acid_purification)</span>, followed by depletion of ribosomal and globin RNA before sequencing. |</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>| Thompson et al. (8) | Whole blood | Analysis of 417 U.S. individuals (353 COVID-19 patients and 64 healthy controls), using baseline (day 0) samples only. Total RNA was extracted from whole blood using magnetic beads, with depletion of ribosomal, globin, and mitochondrial RNA before sequencing. |</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>**Table A1.1**: Dataset descriptions</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="fu"># Appendix 2: Human-infecting virus genera {#appendix-2:-human-infecting-virus-genera}</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a><span class="al">![hv-genera](/img/2025-01-31_figureA2.png)</span> **Figure A2**: Human-infecting virus genera variation across samples in each dataset. Left: Percentage of samples in each dataset that have reads from the human-infecting genera. Right: Relative abundance of human-infecting genera in each dataset (filtered for genera found in <span class="sc">\&gt;</span>5 samples).</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>